# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

# Define services
services:

  # Docker dind "host" must be named docker otherwise TLS certs will fail validation
  docker:
    image: docker:dind
    privileged: true
    # Uncomment tris for insecure Docker TCP communication on 2375
    #environment:
      # DOCKER_TLS_CERTDIR: ''
    volumes:
      # Uncomment tris for insecure Docker TCP communication on 2375
      # - ./daemon.json:/etc/docker/daemon.json
      # Use certs volume to put dind self generated TLS certs for secure communication
      - certs:/certs/client
    expose:
      - 2375
      - 2376
      - 8080
    ports:
      - 8080:8080

  service:
    image: docker:dind
    volumes:
      - .:/app
      - logvolume:/var/log
      - certs:/certs/client
    working_dir: /app
    environment:
      # Uncomment to use insecure communication
      # DOCKER_HOST: 'tcp://docker:2375'
      DOCKER_HOST: 'tcp://docker:2376'
    command: /usr/local/bin/docker-compose -f /app/docker-compose.yaml up
    #command: sh -c "sleep 10000"
    restart: unless-stopped
    depends_on:
      - docker



networks:
  backend:
volumes:
   logvolume: {}
   certs: {}